# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandneove3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/grandneove3g/proprietary/bin/am:system/bin/am \
    vendor/samsung/grandneove3g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/grandneove3g/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/grandneove3g/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/grandneove3g/proprietary/bin/cpu:system/bin/cpu \
    vendor/samsung/grandneove3g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/grandneove3g/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/grandneove3g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/grandneove3g/proprietary/bin/sensorservice:system/bin/sensorservice \
    vendor/samsung/grandneove3g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/grandneove3g/proprietary/bin/slog:system/bin/slog \
    vendor/samsung/grandneove3g/proprietary/bin/slogctl:system/bin/slogctl \
    vendor/samsung/grandneove3g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/grandneove3g/proprietary/bin/smd:system/bin/smd \
    vendor/samsung/grandneove3g/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/grandneove3g/proprietary/bin/vold:system/bin/vold \
    vendor/samsung/grandneove3g/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/samsung/grandneove3g/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/samsung/grandneove3g/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml \
    vendor/samsung/grandneove3g/proprietary/etc/audio_para:system/etc/audio_para \
    vendor/samsung/grandneove3g/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/grandneove3g/proprietary/etc/calib_SI_matrix_data_file.dat:system/etc/calib_SI_matrix_data_file.dat \
    vendor/samsung/grandneove3g/proprietary/etc/clatd.conf:system/etc/clatd.conf \
    vendor/samsung/grandneove3g/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml \
    vendor/samsung/grandneove3g/proprietary/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini \
    vendor/samsung/grandneove3g/proprietary/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini \
    vendor/samsung/grandneove3g/proprietary/etc/event-log-tags:system/etc/event-log-tags \
    vendor/samsung/grandneove3g/proprietary/etc/fallback_fonts.xml:system/etc/fallback_fonts.xml \
    vendor/samsung/grandneove3g/proprietary/etc/feature_default.xml:system/etc/feature_default.xml \
    vendor/samsung/grandneove3g/proprietary/etc/floating_feature.xml:system/etc/floating_feature.xml \
    vendor/samsung/grandneove3g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/grandneove3g/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/grandneove3g/proprietary/etc/hosts:system/etc/hosts \
    vendor/samsung/grandneove3g/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/grandneove3g/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/grandneove3g/proprietary/etc/mkshrc:system/etc/mkshrc \
    vendor/samsung/grandneove3g/proprietary/etc/nwk_info.xml:system/etc/nwk_info.xml \
    vendor/samsung/grandneove3g/proprietary/etc/purenandpackages_pref.txt:system/etc/purenandpackages_pref.txt \
    vendor/samsung/grandneove3g/proprietary/etc/purenandpackages.txt:system/etc/purenandpackages.txt \
    vendor/samsung/grandneove3g/proprietary/etc/recovery-resource.dat:system/etc/recovery-resource.dat \
    vendor/samsung/grandneove3g/proprietary/etc/slog.conf:system/etc/slog.conf \
    vendor/samsung/grandneove3g/proprietary/etc/slog.conf.user:system/etc/slog.conf.user \
    vendor/samsung/grandneove3g/proprietary/etc/spn-conf.xml:system/etc/spn-conf.xml \
    vendor/samsung/grandneove3g/proprietary/etc/system_fonts.xml:system/etc/system_fonts.xml \
    vendor/samsung/grandneove3g/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/grandneove3g/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/grandneove3g/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/grandneove3g/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/grandneove3g/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/grandneove3g/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/grandneove3g/proprietary/lib/lib_SamsungRec_V03010.so:system/lib/lib_SamsungRec_V03010.so \
    vendor/samsung/grandneove3g/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/grandneove3g/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/grandneove3g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/grandneove3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/grandneove3g/proprietary/lib/libjpega.so:system/lib/libjpega.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/grandneove3g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/grandneove3g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/grandneove3g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/grandneove3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/grandneove3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/grandneove3g/proprietary/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
    vendor/samsung/grandneove3g/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/grandneove3g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_aacdec_sprd.so:system/lib/libomx_aacdec_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_apedec_sprd.so:system/lib/libomx_apedec_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/grandneove3g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/grandneove3g/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/grandneove3g/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/grandneove3g/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_gsmdec.so:system/lib/libstagefright_soft_gsmdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_h264dec.so:system/lib/libstagefright_soft_h264dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_h264enc.so:system/lib/libstagefright_soft_h264enc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_imaadpcmdec.so:system/lib/libstagefright_soft_imaadpcmdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_mjpgdec.so:system/lib/libstagefright_soft_mjpgdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_mpeg4enc.so:system/lib/libstagefright_soft_mpeg4enc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_soft_vpxenc.so:system/lib/libstagefright_soft_vpxenc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_aacdec.so:system/lib/libstagefright_sprd_aacdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_h264enc.so:system/lib/libstagefright_sprd_h264enc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_mp3dec.so:system/lib/libstagefright_sprd_mp3dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_mpeg4dec.so:system/lib/libstagefright_sprd_mpeg4dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_soft_h264dec.so:system/lib/libstagefright_sprd_soft_h264dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_soft_mpeg4dec.so:system/lib/libstagefright_sprd_soft_mpeg4dec.so \
    vendor/samsung/grandneove3g/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/samsung/grandneove3g/proprietary/lib/modules/autotst.ko:system/lib/modules/autotst.ko \
    vendor/samsung/grandneove3g/proprietary/lib/modules/mali.ko:system/lib/modules/mali.ko \
    vendor/samsung/grandneove3g/proprietary/lib/modules/mmc_test.ko:system/lib/modules/mmc_test.ko \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/samsung/grandneove3g/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/samsung/grandneove3g/proprietary/lib/ssl/engines/libkeystore.so:system/lib/ssl/engines/libkeystore.so \
    vendor/samsung/grandneove3g/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/grandneove3g/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/samsung/grandneove3g/proprietary/vendor/firmware/BCM43430A1_001.002.009.0013.0018_ORC_GrandNeo_VE.hcd:system/vendor/firmware/BCM43430A1_001.002.009.0013.0018_ORC_GrandNeo_VE.hcd \
    vendor/samsung/grandneove3g/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/grandneove3g/proprietary/vendor/lib/hw/lights.sc8830.so:system/vendor/lib/hw/lights.sc8830.so \
    vendor/samsung/grandneove3g/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/grandneove3g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/grandneove3g/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/grandneove3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/grandneove3g/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/samsung/grandneove3g/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
